### ISSUE TITLE
Exceeds callstack on very large arrays

### ISSUE THREAD

**Issue by Sampsca** [buliasz/AHK_quicksort_array#1]
I find this function very useful, and I thank you for it.  However, I find myself needing to use it on some very large arrays, so large that this function exceeds the callstack limits and ungracefully crashes AHK (v1.1.28.00 on my Win 10 x64 system).  Is there anything that can be done about this, or do you know of any alternative solutions?

TIA,
Sam_

**Comment by buliasz** [comment]
Sorry for late response. Probably you've already found solution, but for those who have the same problem please take a look at this section of Wikipedia article: https://en.wikipedia.org/wiki/Quicksort#Space_complexity

**Comment by Sampsca** [comment]
FWIW, this is the implementation I ended up using:
https://github.com/Sampsca/PS-BAM/blob/master/lib/quick_sort_array_no_recursion.ahk
My version is just a transcoding of the C# code found on codeproject.com that I point to in the code comments.  I'm not sure how the theoretical computational efficiency compares to yours, but it avoids recursion and satisfies my needs.
