### ISSUE TITLE
[Question] Would you please clarify this sentence?

### ISSUE THREAD

**Issue by boolbag** [buliasz/AHK_quicksort_array#2]
https://github.com/buliasz/AHK_quicksort_array/blob/ea2180b5a30a52e05b137dcf03aee903b41bdd20/quick_sort_array.ahk#L1

Hi @buliasz 
Thank you very much for providing this Quick Sort for AHK!

Would you be willing to clarify this comment? I'm not sure I fully understand what you mean.

> Indexes should be continuous (have values under all indexes from the first used, to the last used).

1. By _continuous_, do you mean they should go something like 1, 2, 3…?

2. By _values under all indexes_, what do you mean?

Thanks in advance.

**Comment by buliasz** [comment]
Hi. By continuous I mean with no gaps in indices. You can create array with only two far indexes, eg. 
```
arr[7] := 1
arr[1034] := 3
```
Then this function will go with all numbers starting from 7 to 1034. While it shouldn't be a problem if you use proper comparison, it will usually not have good performance for such arrays.
You can try to change the while loop to go better with such arrays if you need it.

**Comment by boolbag** [comment]
Thank you very much for your explanation. Wishing you a fun weekend.

**Comment by boolbag** [comment]
Hi again! In the spirit of sharing, here's a different QuickSort I just made. It's shorter because it's less general (not passing a comparison function), and it's less general in order to be faster (it's so few lines of code and there are so few use cases that it's easy enough to make a different QuickSort for different purposes). Not debugged! All the best.

```
QuickSort_Alnum(arr) {
      ; Use contiguous index values from 1 up
      
      ; IMPORTANT rather than passing a sort function, to speed things up, it's easy enough
      ; to make a different QuickSort function for each kind of sort
      ; TO MAKE A NEW QUICKSORT, COPY AND EDIT THE THREE LINES COMMENTED BELOW
	length := arr.MaxIndex() ; return the largest integer in the index
	if (length <= 1) {
	   return arr
	}
	pivot := arr[1]
	less_than_pivot := []
	more_than_pivot := []
	Loop % length -1 {
	   to_stash := arr[A_Index + 1]
           ; EDIT THIS LINE #1 (just the comparison condition)
           if (to_stash < pivot) {
	      less_than_pivot.Push(to_stash)
	   }
	   else {
	      more_than_pivot.Push(to_stash)
	   }
	}
	; EDIT THIS LINE #2 (just the function name — recurse)
	sort_builder := QuickSort_Alnum(less_than_pivot)
	sort_builder.Push(pivot)
	; EDIT THIS LINE #3 (just the function name — recurse)
	sorted_above := QuickSort_Alnum(more_than_pivot)
	sort_builder.Push(sorted_above*)
	return sort_builder
}
```

**Comment by buliasz** [comment]
Thank you for sharing.
Best wishes
